

- name: Install apache
  apt:
    name: apache2
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  remote_user: ansible
  become: yes
  become_user: root

- name: Start Apache
  service:
    name: apache2
    state: started
  when: ansible_distribution == "Ubuntu"
  remote_user: ansible
  become: yes
  become_user: root


- name: Copy the apache.conf file
  copy:
    src: /etc/ansible/roles/apache/files/ports.conf
    dest: /etc/apache2/
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Ubuntu"
  remote_user: ansible
  become: yes
  become_user: root
  
- name: Apache Restart
  service:
    name: apache2
    state: restarted
  when: ansible_distribution == "Ubuntu"
  remote_user: ansible
  become: yes
  become_user: root

- name: install IIS WebServer 
  win_feature:
    name: Web-Server
    state: present
    include_sub_features: yes
    include_management_tools: yes
  when: ansible_system == "Win32NT"


